### ISSUE TITLE
Sanitizer breaks @font-face

### ISSUE THREAD

**Issue by mollyporph** [mganss/HtmlSanitizer#80]
The following css: 

```css
@font-face {
        font-family: FrutigerLTStd;
        src: url("https://example.com/FrutigerLTStd-Light.otf") format("opentype");
    }
```

Get's malformed to:
```css
@font-face { font-family: FrutigerLTStd src: url("https://example.com/FrutigerLTStd-Light.otf") format("opentype") }
```
which does not work without a semicolon between font-family and src

using the following rules: 

```csharp
var sanitizer = new HtmlSanitizer();
            sanitizer.AllowDataAttributes = true;
            sanitizer.AllowedAtRules.Add(CssRuleType.Import);
           sanitizer.AllowedAtRules.Add(CssRuleType.FontFace);

            sanitizer.AllowedTags.Add("style");
            sanitizer.AllowedTags.Add("link");
            sanitizer.AllowedTags.Add("picture");

            sanitizer.AllowedAttributes.Add("style");
            sanitizer.AllowedAttributes.Add("class");

            sanitizer.AllowedCssProperties.Add("background-size");
            sanitizer.AllowedCssProperties.Add("box-sizing");
            sanitizer.AllowedCssProperties.Add("position");

            sanitizer.AllowedCssProperties.Add("src");
            sanitizer.AllowedCssProperties.Add("font-family");
```
